#!/usr/bin/env bash
set -euo pipefail

sudo apt update
sudo apt install -y \
  git \
  stow \
  zsh \
  tmux \
  curl \
  wget \
  unzip \
  ripgrep \
  fd-find \
  fzf \
  xclip \
  python3 \
  python3-pip \
  nodejs \
  npm \
  clangd \
  build-essential \
  pkg-config \
  libssl-dev \
  gettext
