require("core.plugin_config.gruvbox")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.rust")
require("core.plugin_config.cmp")
require("core.plugin_config.auto-session")

vim.keymap.set("n", "<leader>dn", ToggleNoDiagnostics, { desc = "Disable diagnostics UI" })
