##### --- General Options ---

# Enable mouse support
set -g mouse on

##### --- Pane Management ---

# Split panes
bind | split-window -h
bind - split-window -v

# Move between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Swap panes
bind H run-shell 'tmux swap-pane -t !; tmux select-pane -L'
bind L run-shell 'tmux swap-pane -t !; tmux select-pane -R'

# Resize panes with Alt + hjkl
bind -n M-h resize-pane -L 2
bind -n M-l resize-pane -R 2
bind -n M-j resize-pane -D 2
bind -n M-k resize-pane -U 2

##### --- Copy Mode ---

# Copy mode uses vi keys
setw -g mode-keys vi

bind -T copy-mode-vi v if-shell -F '#{selection_present}' 'send -X clear-selection' 'send -X begin-selection'
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"

